### ISSUE TITLE
HCaptchaBundle unhandled deprecation ErrorException warning

### ISSUE THREAD

**Issue by rolnavcn** [Meteo-Concept/hcaptcha-bundle#14] opened 2023-12-11 13:43 UTC
The newest version of HCaptchaBundle (v3.4.0) passes **NULL** values to **urlencode()** in **\MeteoConcept\HCaptchaBundle\Service\HCaptchaVerifier::verify**. Passing **NULL** values to **urlencode()** is deprecated and results in an unhandled **ErrorException** warning.

**Comment by lgeorget** [comment] 2023-12-11 17:30
Thank you for the report. I think this error only occurs if the HCaptchaValue is not properly filled-in though so it shouldn't be too much of a problem in normal circumstances since this is a misuse of the HCaptchaVerifier verify() method anyway.

I believe it's fixed in release https://github.com/Meteo-Concept/hcaptcha-bundle/releases/tag/v3.5.0. It's lacking a non-regression test though. #TODO

**Closed as completed** 2023-12-13 08:40 UTC

**Comment by rolnavcn** [comment] 2023-12-13 08:49
It occurred because we pass a **NULL** value to the **$remoteIp** property of **HCaptchaResponse** constructor, since its not necessary.

Thank you for a fast fix!
